import PDFDocument from "pdfkit";
import crypto from "crypto";
import apiError from "../utils/apiError.js";
import {
  getAuthenticatedCloudinaryURL,
  uploadBufferToCloudinary
} from "./cloudinary.storage.service.js";

const PAGE_WIDTH = 495;
const PAGE_LEFT = 50;
const PAGE_RIGHT = 545;
const PAGE_BOTTOM = 780; // safe bottom margin before footer/page overflow
const PAGE_TOP = 50;

const COLORS = {
  primary: '#1e3a8a',
  muted: '#64748b',
  dark: '#0f172a',
  label: '#475569',
  boxBg: '#f8fafc',
  boxBorder: '#cbd5e1',
  danger: '#dc2626',
  dangerBg: '#fef2f2',
  dangerText: '#991b1b',
  dangerTextDark: '#7f1d1d',
  success: '#22c55e',
  successBg: '#f0fdf4',
  successText: '#166534',
  warning: '#f59e0b',
  info: '#3b82f6',
  infoBg: '#eff6ff',
  infoText: '#1e40af',
  infoTextDark: '#1e3a8a'
};

const SEVERITY_COLORS = {
  HIGH: '#ef4444',
  MEDIUM: '#f59e0b',
  LOW: '#22c55e'
};

// Helvetica only supports Latin characters. Strip everything else (Urdu,
// Arabic, hidden/zero-width characters, line separators) so pdfkit never
// draws garbage glyphs or mis-measures / wraps a line.
const safeText = (value) => {
  const text = String(value ?? 'N/A')
    .normalize('NFKC') // turns special spaces into normal ones
    .replace(/[\u200B-\u200F\u2028\u2029\uFEFF]/g, ' ');
  return (
    text
      .replace(/[^\x20-\x7E\u00A0-\u00FF]/g, '')
      .replace(/\s+/g, ' ')
      .trim() || 'N/A'
  );
};

// Values this short are always drawn on a single line (names, phones, emails)
const isShortValue = (value) => safeText(value).length <= 40;

class PDFService {

  static generateContentHash(data) {
    return crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex');
  }

  // Deterministic: the same caseId + type always produces the same document ID,
  // so a regenerated document gets the same ID as the original.
  static generateDocumentId(caseId, type) {
    const fingerprint = crypto
      .createHash('sha256')
      .update(`${type}-${caseId}`)
      .digest('hex')
      .slice(0, 8)
      .toUpperCase();
    return `${type.toUpperCase()}-${new Date().getFullYear()}-${caseId}-${fingerprint}`;
  }

  // ---------------------------------------------------------------------
  // Layout helpers
  // ---------------------------------------------------------------------

  /** Adds a new page if the upcoming content won't fit on the current one. */
  static ensureSpace(doc, neededHeight) {
    if (doc.y + neededHeight > PAGE_BOTTOM) {
      doc.addPage();
      doc.y = PAGE_TOP;
    }
    doc.x = PAGE_LEFT;
  }

  static drawMasthead(doc) {
    doc.fontSize(24).font('Helvetica-Bold').fillColor(COLORS.primary)
      .text('CRIME REPORTING SYSTEM', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(12).font('Helvetica').fillColor(COLORS.muted)
      .text('Multi-Tenant Crime Management Platform', { align: 'center' });
    doc.moveDown(1);
    doc.moveTo(PAGE_LEFT, doc.y).lineTo(PAGE_RIGHT, doc.y)
      .strokeColor(COLORS.boxBorder).lineWidth(1).stroke();
    doc.moveDown(1);
  }

  static drawFooter(doc, { docId, contentHash, notes = [] }) {
    this.ensureSpace(doc, 60 + notes.length * 14);
    doc.x = PAGE_LEFT;
    doc.moveTo(PAGE_LEFT, doc.y).lineTo(PAGE_RIGHT, doc.y)
      .strokeColor(COLORS.boxBorder).lineWidth(1).stroke();
    doc.moveDown(1);
    doc.fontSize(9).font('Helvetica').fillColor(COLORS.muted);
    doc.text('Generated by Crime Reporting System', PAGE_LEFT, doc.y, { width: PAGE_WIDTH, align: 'center' });
    doc.text(`Document ID: ${docId}`, PAGE_LEFT, doc.y, { width: PAGE_WIDTH, align: 'center' });
    doc.text(`Content Hash: ${contentHash}`, PAGE_LEFT, doc.y, { width: PAGE_WIDTH, align: 'center' });
    notes.forEach((note) => {
      doc.moveDown(0.4);
      doc.text(safeText(note), PAGE_LEFT, doc.y, { width: PAGE_WIDTH, align: 'center' });
    });
  }

  /**
   * Bordered box with a title and a list of label/value rows.
   * Short values (names, phone, email) stay on one line. Long values
   * (addresses) wrap inside the box, and the box height is measured to fit.
   */
  static drawInfoBox(doc, { title, rows, bg = COLORS.boxBg, border = COLORS.boxBorder, titleColor = '#1e293b' }) {
    const leftCol = PAGE_LEFT + 15;
    const rightCol = PAGE_LEFT + 200;
    const valueWidth = PAGE_RIGHT - 15 - rightCol;
    const labelWidth = rightCol - leftCol - 10;

    doc.font('Helvetica-Bold').fontSize(10);
    const rowHeights = rows.map(({ value }) => {
      if (isShortValue(value)) return 22;
      return Math.max(22, doc.heightOfString(safeText(value), { width: valueWidth }) + 8);
    });
    const height = 35 + rowHeights.reduce((a, b) => a + b, 0) + 10;

    this.ensureSpace(doc, height + 10);

    const boxTop = doc.y;
    doc.roundedRect(PAGE_LEFT, boxTop, PAGE_WIDTH, height, 5).fillAndStroke(bg, border);
    doc.fillColor(titleColor).fontSize(12).font('Helvetica-Bold')
      .text(title, leftCol, boxTop + 15, { lineBreak: false });

    let rowY = boxTop + 35;
    rows.forEach(({ label, value, valueColor = COLORS.dark }, i) => {
      doc.fillColor(COLORS.label).font('Helvetica').fontSize(10)
        .text(label, leftCol, rowY, { width: labelWidth, lineBreak: false });

      doc.fillColor(valueColor).font('Helvetica-Bold').fontSize(10)
        .text(
          safeText(value),
          rightCol,
          rowY,
          isShortValue(value)
            ? { lineBreak: false }          // short: never wrap
            : { width: valueWidth }         // long: wrap inside the box
        );
      rowY += rowHeights[i];
    });

    doc.x = PAGE_LEFT;
    doc.y = boxTop + height + 10;
  }

  /**
   * Bordered box with a title and a wrapping paragraph. Height is measured
   * from the actual rendered text height.
   */
  static drawParagraphSection(doc, { title, text, bg = COLORS.boxBg, border = COLORS.boxBorder }) {
    const content = text && String(text).trim() ? safeText(text) : 'No description provided';
    const width = PAGE_WIDTH - 30;
    doc.fontSize(10).font('Helvetica');
    const textHeight = doc.heightOfString(content, { width });
    const height = 35 + textHeight + 15;

    this.ensureSpace(doc, height + 10);

    const boxTop = doc.y;
    doc.roundedRect(PAGE_LEFT, boxTop, PAGE_WIDTH, height, 5).fillAndStroke(bg, border);
    doc.fillColor('#1e293b').fontSize(12).font('Helvetica-Bold')
      .text(title, PAGE_LEFT + 15, boxTop + 15, { lineBreak: false });
    doc.fillColor(COLORS.label).fontSize(10).font('Helvetica')
      .text(content, PAGE_LEFT + 15, boxTop + 35, { width });

    doc.x = PAGE_LEFT;
    doc.y = boxTop + height + 10;
  }

  /**
   * Section header + a list of text lines. Not wrapped in one box because the
   * list length is unbounded; each line checks its own space instead.
   */
  static drawListSection(doc, { title, lines, emptyText }) {
    this.ensureSpace(doc, 40);
    doc.fillColor('#1e293b').fontSize(12).font('Helvetica-Bold')
      .text(title, PAGE_LEFT, doc.y, { lineBreak: false });
    doc.moveDown(0.4);
    doc.moveTo(PAGE_LEFT, doc.y).lineTo(PAGE_RIGHT, doc.y)
      .strokeColor(COLORS.boxBorder).lineWidth(1).stroke();
    doc.moveDown(0.5);

    doc.fontSize(9).font('Helvetica').fillColor(COLORS.label);

    if (!lines || lines.length === 0) {
      doc.text(emptyText, PAGE_LEFT + 5, doc.y);
      doc.x = PAGE_LEFT;
      doc.moveDown(1);
      return;
    }

    lines.forEach((rawLine) => {
      const line = safeText(rawLine);
      const lineHeight = doc.heightOfString(line, { width: PAGE_WIDTH - 10 });
      this.ensureSpace(doc, lineHeight + 4);
      doc.fontSize(9).font('Helvetica').fillColor(COLORS.label);
      doc.text(line, PAGE_LEFT + 5, doc.y, { width: PAGE_WIDTH - 10 });
      doc.moveDown(0.2);
    });

    doc.x = PAGE_LEFT;
    doc.moveDown(0.8);
  }

  static async generatePDFBuffer(doc) {
    const chunks = [];

    return await new Promise((resolve, reject) => {
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);
      doc.end();
    });
  }

  // ---------------------------------------------------------------------
  // Public generators
  // ---------------------------------------------------------------------

  /**
   * Generate PDF receipt.
   * Text-only: never embeds or references evidence files.
   * Returns a signed Cloudinary URL.
   */
  static async generateReceipt(caseData, station, tenant) {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50
      });

      this.drawMasthead(doc);

      doc.fontSize(18).font('Helvetica-Bold').fillColor(COLORS.dark)
        .text('CASE ACKNOWLEDGMENT RECEIPT', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica-Oblique').fillColor(COLORS.danger)
        .text('This is an acknowledgment of filing, not a legal certified copy.', { align: 'center' });
      doc.moveDown(1.5);

      const tenantName = tenant?.name || 'N/A';
      const stationName = station?.name || 'N/A';

      this.drawInfoBox(doc, {
        title: 'CASE DETAILS',
        rows: [
          { label: 'Case Reference Number:', value: caseData.caseId },
          { label: 'Filing Date & Time:', value: new Date(caseData.createdAt).toLocaleString() },
          { label: 'Reporting Channel:', value: caseData.reporter?.type === 'GUEST' ? 'Guest Submission (Web)' : 'Citizen Portal (Web)' },
          { label: 'Jurisdiction/Tenant:', value: tenantName },
          { label: 'Assigned Police Station:', value: stationName },
          { label: 'Case Type:', value: caseData.crimeType },
          { label: 'Current Status:', value: 'PENDING REVIEW', valueColor: COLORS.warning }
        ]
      });

      this.drawInfoBox(doc, {
        title: 'INCIDENT LOCATION',
        rows: [
          { label: 'Location:', value: caseData.locationLabel || 'Not specified' },
          { label: 'Address Details:', value: caseData.address || 'N/A' }
        ]
      });

      if (station) {
        const sho = station.stationHead;

        const stationRows = [
          { label: 'Station Address:', value: station.address || 'N/A' },
          { label: 'City:', value: station.city || 'N/A' },
          { label: 'Station Contact Number:', value: station.contactNumber || 'N/A' },
          { label: 'Station Email:', value: station.email || 'N/A' }
        ];
        if (sho?.fullName) {
          stationRows.push({ label: 'Station Head:', value: sho.fullName });
          if (sho.badgeNumber) {
            stationRows.push({ label: 'SHO Badge Number:', value: sho.badgeNumber });
          }
          stationRows.push({ label: 'SHO Contact:', value: sho.phone || sho.email || 'N/A' });
        }

        this.drawInfoBox(doc, { title: 'STATION CONTACT', rows: stationRows });
      }

      this.drawInfoBox(doc, {
        title: 'REPORTER INFORMATION',
        rows: [
          { label: 'Reporter Type:', value: caseData.reporter?.type },
          { label: 'Full Name:', value: caseData.reporter?.fullName },
          { label: 'Email:', value: caseData.reporter?.email },
          { label: 'Phone:', value: caseData.reporter?.phone }
        ]
      });

      this.ensureSpace(doc, 75);
      const trackTop = doc.y;
      doc.roundedRect(PAGE_LEFT, trackTop, PAGE_WIDTH, 60, 5).fillAndStroke(COLORS.infoBg, COLORS.info);
      doc.fillColor(COLORS.infoText).fontSize(11).font('Helvetica-Bold')
        .text('TRACKING INFORMATION', PAGE_LEFT + 15, trackTop + 15, { lineBreak: false });
      doc.fontSize(10).font('Helvetica').fillColor(COLORS.infoTextDark)
        .text('Use this tracking code to check your case status: ', PAGE_LEFT + 15, trackTop + 35, { continued: true, lineBreak: false });
      doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.dark)
        .text(safeText(caseData.caseId), { lineBreak: false });
      doc.x = PAGE_LEFT;
      doc.y = trackTop + 75;

      const docId = this.generateDocumentId(caseData.caseId, 'ACK');
      const contentHash = this.generateContentHash(caseData);
      this.drawFooter(doc, {
        docId,
        contentHash,
        notes: ['This document is auto-generated. For any queries, contact the police station.']
      });

      const pdfBuffer = await this.generatePDFBuffer(doc);

      const uploaded = await uploadBufferToCloudinary(pdfBuffer, {
        folder: `crime_saas/pdfs/receipts/${caseData._id}`,
        resourceType: "raw",
        filename: `${caseData.caseId}-receipt.pdf`,
        deliveryType: "authenticated"
      });

      return getAuthenticatedCloudinaryURL(uploaded.public_id, uploaded.version);
    } catch (err) {
      console.error("Receipt PDF generation failed:", err);
      throw err instanceof apiError ? err : new apiError(500, "Receipt PDF generation failed");
    }
  }

  /**
   * Generate the full internal case report after closure (station head only).
   * Text-only: the Evidence section reports only a file count.
   * Returns a signed Cloudinary URL.
   */
  static async generateFullCase(caseData, updates, evidenceCount) {
    if (caseData.status && caseData.status !== "CLOSED") {
      throw new apiError(400, "Full PDF can only be generated for closed cases");
    }

    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });

      this.drawMasthead(doc);

      doc.fontSize(18).font('Helvetica-Bold').fillColor(COLORS.dark)
        .text('CASE FINAL REPORT', { align: 'center' });
      doc.fontSize(10).font('Helvetica').fillColor(COLORS.success)
        .text('CASE CLOSED', { align: 'center' });
      doc.fontSize(10).font('Helvetica').fillColor(COLORS.danger)
        .text('AUTHORIZED PERSONNEL ONLY', { align: 'center' });
      doc.moveDown(1.5);

      const severityColor = SEVERITY_COLORS[caseData.severity] || COLORS.muted;

      const caseDetailRows = [
        { label: 'Case Reference Number:', value: caseData.caseId },
        { label: 'Filing Date:', value: new Date(caseData.createdAt).toLocaleDateString() },
        { label: 'Closure Date:', value: new Date(caseData.closedAt).toLocaleDateString() },
        { label: 'Case Type:', value: caseData.crimeType },
        { label: 'Severity:', value: caseData.severity, valueColor: severityColor },
        { label: 'Final Status:', value: 'CLOSED', valueColor: COLORS.success }
      ];
      if (caseData.assignedTo) {
        caseDetailRows.push({ label: 'Assigned Officer:', value: caseData.assignedTo.fullName || 'N/A' });
      }
      this.drawInfoBox(doc, { title: 'CASE DETAILS', rows: caseDetailRows });

      this.drawInfoBox(doc, {
        title: 'REPORTER INFORMATION',
        rows: [
          { label: 'Reporter Type:', value: caseData.reporter?.type },
          { label: 'Full Name:', value: caseData.reporter?.fullName },
          { label: 'Email:', value: caseData.reporter?.email },
          { label: 'Phone:', value: caseData.reporter?.phone }
        ]
      });

      this.drawInfoBox(doc, {
        title: 'POLICE STATION',
        rows: [
          { label: 'Station Name:', value: caseData.policeStationId?.name || 'N/A' },
          { label: 'Station Head:', value: caseData.policeStationId?.stationHead?.fullName || 'N/A' },
          { label: 'Station Contact:', value: caseData.policeStationId?.contactNumber || 'N/A' },
          { label: 'Station Address:', value: caseData.policeStationId?.locationLabel || 'N/A' }
        ]
      });

      this.drawInfoBox(doc, {
        title: 'ASSIGNED OFFICER',
        rows: [
          { label: 'Officer Name:', value: caseData.assignedTo?.fullName || 'N/A' },
          { label: 'Officer Badge Number:', value: caseData.assignedTo?.badgeNumber || 'N/A' },
          { label: 'Officer Contact:', value: caseData.assignedTo?.phone || 'N/A' },
          { label: 'Officer Email:', value: caseData.assignedTo?.email || 'N/A' }
        ]
      });

      this.drawParagraphSection(doc, { title: 'CASE SUMMARY', text: caseData.aiSummary || caseData.description });

      const timelineLines = (updates || []).map((update) => {
        const dateStr = new Date(update.createdAt).toLocaleString();
        return `• ${dateStr} - ${update.updateType}: ${update.remarks || update.newStatus || 'No remarks'}`;
      });
      this.drawListSection(doc, {
        title: 'INVESTIGATION TIMELINE',
        lines: timelineLines,
        emptyText: 'No updates recorded'
      });

      this.drawInfoBox(doc, {
        title: 'INCIDENT LOCATION',
        rows: [
          { label: 'Location:', value: caseData.locationLabel || 'Not specified' },
          { label: 'Address Details:', value: caseData.address || 'N/A' }
        ]
      });

      // Text-only count. Does not embed or link to actual evidence files.
      this.drawInfoBox(doc, {
        title: 'EVIDENCE SUMMARY',
        rows: [{ label: 'Total Evidence Files:', value: evidenceCount || 0 }]
      });

      // Officer notes box
      this.ensureSpace(doc, 80);
      const notesTop = doc.y;
      doc.roundedRect(PAGE_LEFT, notesTop, PAGE_WIDTH, 70, 5).fillAndStroke(COLORS.dangerBg, COLORS.danger);
      doc.fillColor(COLORS.dangerText).fontSize(12).font('Helvetica-Bold')
        .text('OFFICER NOTES (INTERNAL)', PAGE_LEFT + 15, notesTop + 15, { lineBreak: false });
      doc.fontSize(9).font('Helvetica').fillColor(COLORS.dangerTextDark)
        .text('Internal investigation notes are available in the system.', PAGE_LEFT + 15, notesTop + 35, { lineBreak: false });
      doc.x = PAGE_LEFT;
      doc.y = notesTop + 80;

      // Closure information box
      this.ensureSpace(doc, 80);
      const closureTop = doc.y;
      const closureWidth = PAGE_WIDTH - 30;
      doc.roundedRect(PAGE_LEFT, closureTop, PAGE_WIDTH, 70, 5).fillAndStroke(COLORS.successBg, COLORS.success);
      doc.fillColor(COLORS.successText).fontSize(12).font('Helvetica-Bold')
        .text('CLOSURE INFORMATION', PAGE_LEFT + 15, closureTop + 15, { width: closureWidth, lineBreak: false });
      doc.fontSize(10).font('Helvetica').fillColor(COLORS.successText)
        .text(`Closed By: ${safeText(caseData.closedBy?.fullName)}`, PAGE_LEFT + 15, closureTop + 35, { width: closureWidth, lineBreak: false });
      doc.text(`Closure Reason: ${safeText(caseData.closureReason || 'Case closed')}`, PAGE_LEFT + 15, closureTop + 50, { width: closureWidth, lineBreak: false });
      doc.x = PAGE_LEFT;
      doc.y = closureTop + 80;

      const docId = this.generateDocumentId(caseData.caseId, 'FINAL');
      const contentHash = this.generateContentHash(caseData);
      this.drawFooter(doc, {
        docId,
        contentHash,
        notes: ['Classification: INTERNAL - AUTHORIZED PERSONNEL ONLY']
      });

      const pdfBuffer = await this.generatePDFBuffer(doc);

      const uploaded = await uploadBufferToCloudinary(pdfBuffer, {
        folder: `crime_saas/pdfs/final-reports/${caseData._id}`,
        resourceType: "raw",
        filename: `${caseData.caseId}-full.pdf`,
        deliveryType: "authenticated"
      });

      return getAuthenticatedCloudinaryURL(uploaded.public_id, uploaded.version);
    } catch (err) {
      console.error("Full case PDF generation failed:", err);
      throw err instanceof apiError ? err : new apiError(500, "Full case PDF generation failed");
    }
  }
}

export default PDFService;



// for local pdf storage 
// import fs from "fs";
// import path from "path";


  // for local pdf storage
  // static generateFilePath(caseId, type) {
  //   const dir = path.join("uploads", "pdfs");

  //   if (!fs.existsSync(dir)) {
  //     fs.mkdirSync(dir, { recursive: true });
  //   }

  //   return path.join(dir, `${caseId}-${type}.pdf`);
  // }

  // static async finalizeDocument(doc, stream, filePath) {
  //   doc.end();
  //   try {
  //     await new Promise((resolve, reject) => {
  //       stream.on('finish', resolve);
  //       stream.on('error', reject);
  //     });
  //   } catch (err) {
  //     fs.unlink(filePath, () => {});
  //     throw err;
  //   }
  //   return filePath;
  // }


 //local
    // const filePath = this.generateFilePath(caseData.caseId, "receipt");
    // const doc = new PDFDocument({ size: 'A4', margin: 50 });
    // const stream = fs.createWriteStream(filePath);
    // doc.pipe(stream);